(function(){
'use strict';
let root=null,sourceText='',sourceInfo=null,busy=false;
function core(){return window.UKMLA_V2;}
function ai(){return window.UKMLA_V2_AI;}
function schema(){return window.UKMLA_V2_AI_SCHEMA;}
function transport(){return window.UKMLA_V2_AI_TRANSPORT;}
function clean(value){return core().clean(value);}
function emit(message,percent){if(!root)return;const status=root.querySelector('#knowledge-status'),fill=root.querySelector('#knowledge-fill'),label=root.querySelector('#knowledge-percent');if(status)status.textContent=message;if(fill)fill.style.setProperty('--value',`${percent}%`);if(label)label.textContent=`${Math.round(percent)}%`;}
function mapSchema(){return{type:'object',additionalProperties:false,required:['packId','title','inferredTopic','concepts'],properties:{packId:{type:'string'},title:{type:'string'},inferredTopic:{type:'string'},concepts:{type:'array',minItems:10,maxItems:100,items:{type:'object',additionalProperties:false,required:['id','label','topicName','summary','importance','clinicalRelevance','sourceRefs','supportedQuestionTypes'],properties:{id:{type:'string'},label:{type:'string'},topicName:{type:'string'},summary:{type:'string'},importance:{type:'integer',minimum:1,maximum:10},clinicalRelevance:{type:'integer',minimum:1,maximum:10},sourceRefs:{type:'array',minItems:1,items:{type:'string'}},supportedQuestionTypes:{type:'array',minItems:1,items:{type:'string',enum:schema().TYPES.map(item=>item[0])}}}}}}};}
function simpleHash(value){let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(36);}
function packIdFor(text){return`pack-${simpleHash(text)}`;}
async function requestMap(token,packId,title,text){const prompt=`Convert the supplied course material into a comprehensive examinable knowledge map for UKMLA-style SBA training. Cover the whole source, not only the opening section. Split broad material into distinct clinically useful concepts. Preserve source provenance using slide labels or text-section labels. Do not invent facts. For each concept, list only question types the material genuinely supports. The packId must be ${packId}.\n\nSOURCE TITLE: ${title}\n\nSOURCE MATERIAL:\n${text.slice(0,140000)}`;const body={model:'gpt-5-mini',input:[{role:'system',content:[{type:'input_text',text:'Return only the requested schema-conforming knowledge map.'}]},{role:'user',content:[{type:'input_text',text:prompt}]}],text:{format:{type:'json_schema',name:'ukmla_knowledge_map_v2',strict:true,schema:mapSchema()}}};const data=await transport().send(token,body);const raw=schema().outputText(data);if(!raw)throw new Error('No knowledge map was returned.');return JSON.parse(raw);}
async function buildMap(token,packId,title,text){const packs=core().loadJson(core().STORAGE.knowledge,{});if(packs[packId]?.map)return packs[packId].map;const map=await requestMap(token,packId,title,text);map.packId=packId;map.title=title;packs[packId]={packId,title,map,sourceKind:sourceInfo?.kind||'text',sourceFile:sourceInfo?.fileName||null,sourceLength:text.length,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};core().saveJson(core().STORAGE.knowledge,packs);return map;}
function weakTypeOrder(){const stats=core().eventIndex().type;return schema().TYPES.map(item=>({id:item[0],answered:stats[item[0]]?.answered||0,accuracy:stats[item[0]]?.answered?stats[item[0]].correct/stats[item[0]].answered:null})).sort((a,b)=>{if(a.accuracy===null&&b.accuracy!==null)return 1;if(a.accuracy!==null&&b.accuracy===null)return-1;return(a.accuracy??1)-(b.accuracy??1)||b.answered-a.answered;}).map(item=>item.id);}
function conceptStats(packId){const result={};for(const event of core().eventIndex().presentations.filter(item=>item.packId===packId)){const row=result[event.conditionId]||(result[event.conditionId]={presented:0,last:null});row.presented++;row.last=event.at;}return result;}
function rankConcepts(map,packId,exclude){const stats=conceptStats(packId),now=Date.now();return map.concepts.slice().sort((a,b)=>{const aid=`${packId}-${a.id}`,bid=`${packId}-${b.id}`;const sa=stats[aid]||{presented:0,last:null},sb=stats[bid]||{presented:0,last:null};const ea=exclude.has(aid)?1:0,eb=exclude.has(bid)?1:0;const ta=sa.last?now-new Date(sa.last).getTime():Number.MAX_SAFE_INTEGER,tb=sb.last?now-new Date(sb.last).getTime():Number.MAX_SAFE_INTEGER;return ea-eb||(sa.presented===0?0:1)-(sb.presented===0?0:1)||sa.presented-sb.presented||b.importance-a.importance||b.clinicalRelevance-a.clinicalRelevance||tb-ta||Math.random()-.5;});}
function assignConcepts(map,packId,typeOrder,exclude){const ranked=rankConcepts(map,packId,exclude),selected=[],used=new Set();for(const type of typeOrder){let concept=ranked.find(item=>!used.has(item.id)&&(item.supportedQuestionTypes||[]).includes(type));if(!concept)concept=ranked.find(item=>!used.has(item.id));if(!concept)concept=ranked.find(item=>(item.supportedQuestionTypes||[]).includes(type))||ranked[0];if(concept){selected.push({concept,type});used.add(concept.id);}}return selected;}
function conceptCondition(pair,packId,title){const concept=pair.concept,topicName=concept.topicName||title,topicId=`pack-${simpleHash(packId)}-${simpleHash(topicName)}`;return{id:`${packId}-${concept.id}`,conditionId:`${packId}-${concept.id}`,topicId,topic:topicName,topicName,name:concept.label,profile:'knowledge',fields:{investigations:concept.summary,treatment:concept.summary,escalation:concept.summary,mimics:concept.summary,redFlags:concept.summary},labels:{investigations:'Source concept',treatment:'Source concept',escalation:'Source concept',mimics:'Source concept',redFlags:'Source concept'},sourceRefs:concept.sourceRefs,importance:concept.importance,clinicalRelevance:concept.clinicalRelevance};}
function combineSets(sets,count,packId,title){const questions=[];for(const set of sets)for(const question of set.questions)questions.push(question);questions.length=count;questions.forEach((question,index)=>{question.questionNumber=index+1;question.id=`${packId}-q${index+1}`;});return{schemaVersion:'ukmla-ai-quiz-v2',quizId:`knowledge-${packId}-${Date.now().toString(36)}`,topic:title,generatedAt:new Date().toISOString(),difficulty:'very_difficult',sourceType:'knowledge_dump',packId,questions};}
async function generate(){if(busy)return;const token=clean(root.querySelector('#knowledge-key').value),text=clean(sourceText||root.querySelector('#knowledge-text').value);if(token.length<20){core().toast('Paste the temporary session key.');return;}if(text.length<120){core().toast('Add more source material first.');return;}busy=true;root.querySelectorAll('button').forEach(button=>button.disabled=true);const count=Number(root.querySelector('#knowledge-count').value),title=clean(root.querySelector('#knowledge-title').value)||sourceInfo?.fileName||'Uploaded study material',packId=packIdFor(text);try{emit('Inferring the most pertinent concepts from the source…',8);const map=await buildMap(token,packId,title,text);emit(`${map.concepts.length} source concepts identified.`,18);const batches=Math.ceil(count/10),sets=[],exclude=new Set(),standard=schema().TYPES.map(item=>item[0]),weak=weakTypeOrder();for(let batch=0;batch<batches;batch++){const types=batch===0?standard:weak,assignments=assignConcepts(map,packId,types,exclude);if(assignments.length!==10)throw new Error('The source map did not provide ten usable concepts.');const conditions=assignments.map(pair=>conceptCondition(pair,packId,title));conditions.forEach(item=>exclude.add(item.id));const set=await ai().runKnowledgeBatch({apiKey:token,conditions,questionTypes:types,topic:title,sourceTitle:title,packId,knowledge:true,persist:false,onProgress:(message,percent)=>emit(`${batch+1}/${batches}: ${message}`,Math.min(94,18+batch*(72/batches)+percent*(72/batches)/100))});sets.push(set);}emit('Combining the final question set…',96);const combined=combineSets(sets,count,packId,title);ai().storeSet(combined);ai().renderSet(root.querySelector('#knowledge-play'),combined,'knowledge');emit(`${count}-question source-grounded quiz ready.`,100);}catch(error){emit(`Generation stopped: ${error.message}`,0);}finally{busy=false;root.querySelectorAll('button').forEach(button=>button.disabled=false);root.querySelector('#knowledge-key').value='';sourceText=text;}}
async function loadFile(file){try{emit(`Extracting ${file.name}…`,2);const result=await window.UKMLA_V2_PPTX.readFile(file);sourceText=result.text;sourceInfo=result.info;root.querySelector('#knowledge-text').value=result.text;root.querySelector('#knowledge-title').value=file.name.replace(/\.[^.]+$/,'');root.querySelector('#knowledge-file-info').textContent=result.info.kind==='pptx'?`${result.info.slides} slides processed; ${result.info.slidesWithText} contained extractable text; ${result.info.emptySlides} contained no extractable text.`:`Loaded ${file.name}: ${result.text.length.toLocaleString()} characters.`;emit('Source extracted and ready.',5);}catch(error){emit(`File extraction failed: ${error.message}`,0);}}
function mount(container){root=container;root.innerHTML=`<div class="page-head"><div><div class="eyebrow">Source-grounded SBA training</div><h1>Knowledge dump</h1><p>Drop PowerPoint slides or paste course notes. The AI maps the whole source before generating questions through every quality checkpoint.</p></div></div><section class="quiz-layout"><article class="panel"><div class="drop-zone" id="knowledge-drop"><div><strong>Drop a .pptx or text file</strong><p>or tap to choose a file</p><input id="knowledge-file" type="file" accept=".pptx,.txt,.md,.csv,.json,.html,.htm,.rtf" hidden></div></div><textarea class="textarea" id="knowledge-text" placeholder="Paste lecture notes, handouts or coursework material here…"></textarea></article><aside class="panel"><div class="field"><label>Pack title</label><input class="input" id="knowledge-title" placeholder="e.g. Renal seminar"></div><div class="field" style="margin-top:12px"><label>Question count</label><select class="select" id="knowledge-count"><option value="10">10 questions</option><option value="15">15 questions</option><option value="20">20 questions</option></select></div><div class="field" style="margin-top:12px"><label>Temporary OpenAI API key</label><input class="input" type="password" id="knowledge-key" autocomplete="off" placeholder="Paste session key"></div><button class="btn primary" id="knowledge-generate" style="width:100%;margin-top:16px">Generate source-grounded quiz</button><p id="knowledge-file-info" style="color:var(--muted)">No file loaded.</p><div class="topic-meta"><span id="knowledge-status">Waiting for study material.</span><strong id="knowledge-percent">0%</strong></div><div class="progress-track" style="margin-top:10px"><div class="progress-fill" id="knowledge-fill" style="--value:0%"></div></div></aside></section><section id="knowledge-play" style="margin-top:18px"></section>`;const drop=root.querySelector('#knowledge-drop'),fileInput=root.querySelector('#knowledge-file'),textarea=root.querySelector('#knowledge-text');drop.onclick=()=>fileInput.click();['dragenter','dragover'].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.add('drag');}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.remove('drag');}));drop.addEventListener('drop',event=>{const file=event.dataTransfer.files[0];if(file)loadFile(file);});fileInput.onchange=()=>{const file=fileInput.files[0];if(file)loadFile(file);};textarea.oninput=()=>{sourceText=textarea.value;sourceInfo={kind:'text',fileName:null};root.querySelector('#knowledge-file-info').textContent=`${sourceText.length.toLocaleString()} characters pasted.`;};root.querySelector('#knowledge-generate').onclick=generate;}
window.UKMLA_V2_KNOWLEDGE={mount};
})();
