(function(){
'use strict';
function clean(value){return String(value||'').replace(/\s+/g,' ').trim();}
function findEocd(view){for(let i=view.byteLength-22;i>=Math.max(0,view.byteLength-65557);i--)if(view.getUint32(i,true)===0x06054b50)return i;return-1;}
async function inflateRaw(bytes){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decompress PowerPoint files. Paste the slide text instead.');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(stream).arrayBuffer());}
async function unzip(buffer){const view=new DataView(buffer);const eocd=findEocd(view);if(eocd<0)throw new Error('The PowerPoint ZIP directory could not be found.');const entries=view.getUint16(eocd+10,true);let offset=view.getUint32(eocd+16,true);const decoder=new TextDecoder();const files=new Map();for(let i=0;i<entries;i++){if(view.getUint32(offset,true)!==0x02014b50)throw new Error('The PowerPoint ZIP directory is damaged.');const method=view.getUint16(offset+10,true);const compressed=view.getUint32(offset+20,true);const nameLen=view.getUint16(offset+28,true);const extraLen=view.getUint16(offset+30,true);const commentLen=view.getUint16(offset+32,true);const localOffset=view.getUint32(offset+42,true);const name=decoder.decode(new Uint8Array(buffer,offset+46,nameLen));if(view.getUint32(localOffset,true)!==0x04034b50)throw new Error('A PowerPoint ZIP entry is invalid.');const localName=view.getUint16(localOffset+26,true);const localExtra=view.getUint16(localOffset+28,true);const dataStart=localOffset+30+localName+localExtra;const bytes=new Uint8Array(buffer,dataStart,compressed);if(method===0)files.set(name,new Uint8Array(bytes));else if(method===8)files.set(name,await inflateRaw(bytes));offset+=46+nameLen+extraLen+commentLen;}return files;}
function xmlText(bytes){const xml=new TextDecoder().decode(bytes);const doc=new DOMParser().parseFromString(xml,'application/xml');return[...doc.getElementsByTagName('*')].filter(node=>node.localName==='t').map(node=>clean(node.textContent)).filter(Boolean).join(' · ');}
async function extractPptx(file){const files=await unzip(await file.arrayBuffer());const slides=[...files.keys()].filter(name=>/^ppt\/slides\/slide\d+\.xml$/.test(name)).sort((a,b)=>Number(a.match(/(\d+)/)[1])-Number(b.match(/(\d+)/)[1]));const chunks=[];let slidesWithText=0;slides.forEach((name,index)=>{const number=Number(name.match(/(\d+)/)[1]);const text=xmlText(files.get(name));const notesName=`ppt/notesSlides/notesSlide${number}.xml`;const notes=files.has(notesName)?xmlText(files.get(notesName)):'';if(text||notes)slidesWithText++;chunks.push(`[Slide ${index+1}]\n${text||'[No extractable slide text]'}${notes?`\n[Speaker notes] ${notes}`:''}`);});return{text:chunks.join('\n\n'),info:{kind:'pptx',fileName:file.name,slides:slides.length,slidesWithText,emptySlides:slides.length-slidesWithText}};}
async function readFile(file){const extension=file.name.split('.').pop().toLowerCase();if(extension==='pptx')return extractPptx(file);if(['txt','md','csv','json','html','htm','rtf'].includes(extension))return{text:await file.text(),info:{kind:'text',fileName:file.name}};throw new Error('Use a .pptx or text-based file.');}
window.UKMLA_V2_PPTX={readFile};
})();
