(function(){
  'use strict';

  const UI_KEY='ukmlaPsaUiStateV1';
  let root=null;
  let currentPaper=null;
  let currentSession=null;
  let sessionToken='';
  let timerId=null;
  let lastItemEnteredAt=0;
  let generationRunning=false;
  let markingRunning=false;

  function core(){return window.UKMLA_V2;}
  function schema(){return window.UKMLA_PSA_SCHEMA;}
  function engine(){return window.UKMLA_PSA_ENGINE;}
  function clean(value){return core().clean(value);}
  function escapeHtml(value){return core().escapeHtml(value);}
  function uiState(){return core().loadJson(UI_KEY,{mode:'half',sectionId:'prescribing',count:5});}
  function saveUi(patch){core().saveJson(UI_KEY,{...uiState(),...patch});}
  function formatTime(seconds){const safe=Math.max(0,Math.round(seconds||0)),minutes=Math.floor(safe/60),remainder=safe%60;return`${minutes}:${String(remainder).padStart(2,'0')}`;}
  function deviceId(){let id=localStorage.getItem(core().STORAGE.device);if(!id){id=`device-${Math.random().toString(36).slice(2,9)}-${Date.now().toString(36)}`;localStorage.setItem(core().STORAGE.device,id);}return id;}
  function hasPrescriptionItems(paper){return paper.items.some(item=>item.responseMode==='prescription');}
  function paperSectionMeta(item){return schema().section(item.sectionId);}
  function modeLabel(mode){return mode==='full'?'Full 60-item PSA':mode==='half'?'30-item half paper':'Section drill';}

  function integrate(){
    if(!window.UKMLA_V2||!document.getElementById('app'))return;
    const hash=location.hash;
    if(hash.startsWith('#/quiz'))integrateQuizTab();
    if(hash.startsWith('#/analytics'))integrateAnalyticsButton();
  }
  function integrateQuizTab(){
    const tabs=document.querySelector('#app .tabs'),workspace=document.getElementById('quiz-workspace');
    if(!tabs||!workspace||tabs.querySelector('[data-quiz-tab="psa"]'))return;
    const button=document.createElement('button');button.className='tab';button.dataset.quizTab='psa';button.textContent='PSA';tabs.appendChild(button);
    button.onclick=()=>{
      tabs.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab===button));
      mount(workspace);
    };
  }
  function integrateAnalyticsButton(){
    const head=document.querySelector('#app .page-head');
    if(!head||head.querySelector('#open-psa-analytics'))return;
    let actions=head.querySelector('.page-actions');
    if(!actions){actions=document.createElement('div');actions.className='page-actions';head.appendChild(actions);}
    const button=document.createElement('button');button.id='open-psa-analytics';button.className='btn primary';button.textContent='PSA analytics';button.onclick=renderAnalytics;actions.appendChild(button);
  }

  function mount(container){
    root=container;
    stopTimer();
    currentSession=engine().activeSession();
    currentPaper=currentSession?engine().paperById(currentSession.paperId):engine().latestPaper();
    if(currentSession&&currentPaper){renderExam();return;}
    renderSetup();
  }

  function renderSetup(){
    const state=uiState(),job=engine().loadGenerationJob(),paper=currentPaper||engine().latestPaper();
    root.innerHTML=`<section class="psa-hero"><div><div class="eyebrow">Prescribing Safety Assessment</div><h2>Open-book prescribing under time pressure</h2><p>Generate original PSA-style practice with official section weighting, BNF navigation tracking, persistent timing, and audited marking.</p></div><div class="psa-mark-ring"><strong>200</strong><span>marks in a full paper</span></div></section>
    <section class="quiz-layout psa-setup-grid"><article class="quiz-card"><h2>Build a practice paper</h2><div class="field"><label>Mode</label><select class="select" id="psa-mode"><option value="half" ${state.mode==='half'?'selected':''}>30-item half paper · 60 minutes</option><option value="full" ${state.mode==='full'?'selected':''}>60-item full paper · 120 minutes</option><option value="section" ${state.mode==='section'?'selected':''}>Single-section drill</option></select></div><div id="psa-section-settings" ${state.mode==='section'?'':'hidden'}><div class="field" style="margin-top:12px"><label>Section</label><select class="select" id="psa-section">${schema().SECTIONS.map(item=>`<option value="${item.id}" ${state.sectionId===item.id?'selected':''}>${escapeHtml(item.label)} · ${item.marks} marks each</option>`).join('')}</select></div><div class="field" style="margin-top:12px"><label>Items</label><select class="select" id="psa-count">${[3,5,8,10].map(count=>`<option value="${count}" ${Number(state.count)===count?'selected':''}>${count} items</option>`).join('')}</select></div></div><div class="field" style="margin-top:12px"><label>Temporary OpenAI API key</label><input class="input" id="psa-key" type="password" autocomplete="off" placeholder="Paste session key"></div><p class="psa-cost-note">Generation uses three API checkpoints for every included section. A full paper therefore takes substantially longer than an ordinary SBA set.</p><button class="btn primary" id="psa-generate" style="width:100%">Generate audited PSA paper</button>${job&&job.status!=='complete'?'<button class="btn" id="psa-resume-generation" style="width:100%;margin-top:9px">Resume saved generation</button><button class="btn danger" id="psa-discard-generation" style="width:100%;margin-top:9px">Discard generation</button>':''}${paper?`<button class="btn ghost" id="psa-start-latest" style="width:100%;margin-top:9px">Start latest ${paper.totalItems}-item paper</button>`:''}</article><aside class="quiz-card"><div class="topic-meta"><span>Generation checkpoints</span><strong id="psa-generation-percent">${job?.percent||0}%</strong></div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" id="psa-generation-fill" style="--value:${job?.percent||0}%"></div></div><div id="psa-generation-section" class="psa-current-stage">${escapeHtml(job?.lastMessage||'Ready to generate.')}</div><div class="checkpoint-list" id="psa-generation-checkpoints">${generationCheckpointHtml(job)}</div><h3>Official full-paper weighting</h3><div class="psa-blueprint-mini">${schema().SECTIONS.map(item=>`<div><span>${escapeHtml(item.label)}</span><strong>${item.officialCount} · ${item.totalMarks} marks</strong></div>`).join('')}</div></aside></section>`;
    const mode=root.querySelector('#psa-mode');mode.onchange=()=>{root.querySelector('#psa-section-settings').hidden=mode.value!=='section';saveUi({mode:mode.value});};root.querySelector('#psa-section').onchange=event=>saveUi({sectionId:event.target.value});root.querySelector('#psa-count').onchange=event=>saveUi({count:Number(event.target.value)});root.querySelector('#psa-generate').onclick=()=>generate(false);root.querySelector('#psa-resume-generation')?.addEventListener('click',()=>generate(true));root.querySelector('#psa-discard-generation')?.addEventListener('click',()=>{engine().clearGenerationJob();renderSetup();});root.querySelector('#psa-start-latest')?.addEventListener('click',()=>startPaper(paper));
  }
  function generationCheckpointHtml(job){
    const currentSection=job?.currentSectionId?schema().section(job.currentSectionId):null;
    return schema().GENERATION_STAGES.map(stage=>{const active=job?.currentStage===stage.id&&job?.status!=='complete';const stageIndex=schema().GENERATION_STAGES.findIndex(item=>item.id===stage.id);const done=job&&(job.sectionIndex>0||job.stageIndex>stageIndex||job.status==='complete')&&!active;return`<div class="checkpoint ${done?'done':''} ${active?'active':''}"><span class="checkpoint-dot"></span><span>${escapeHtml(stage.label)}${active&&currentSection?` · ${escapeHtml(currentSection.label)}`:''}</span></div>`;}).join('');
  }
  function updateGeneration(job){
    if(!root)return;const percent=root.querySelector('#psa-generation-percent'),fill=root.querySelector('#psa-generation-fill'),message=root.querySelector('#psa-generation-section'),list=root.querySelector('#psa-generation-checkpoints');if(percent)percent.textContent=`${job?.percent||0}%`;if(fill)fill.style.setProperty('--value',`${job?.percent||0}%`);if(message)message.textContent=job?.lastMessage||'';if(list)list.innerHTML=generationCheckpointHtml(job);
  }
  async function generate(resume){
    if(generationRunning)return;const token=clean(root.querySelector('#psa-key').value);if(token.length<20){core().toast('Paste the temporary session key.');return;}generationRunning=true;root.querySelectorAll('button').forEach(button=>button.disabled=true);
    try{
      const job=resume?engine().loadGenerationJob():null;const state=uiState();const mode=job?.mode||root.querySelector('#psa-mode').value;saveUi({mode,sectionId:root.querySelector('#psa-section').value,count:Number(root.querySelector('#psa-count').value)});const paper=await engine().generatePaper({apiKey:token,mode,sectionId:root.querySelector('#psa-section').value,count:Number(root.querySelector('#psa-count').value),job});currentPaper=paper;sessionToken=token;core().toast(`${paper.totalItems}-item PSA paper ready.`);renderSetup();
    }catch(error){core().toast(`PSA generation stopped: ${error.message}`);updateGeneration(engine().loadGenerationJob());}
    finally{generationRunning=false;root?.querySelectorAll('button').forEach(button=>button.disabled=false);const key=root?.querySelector('#psa-key');if(key)key.value='';}
  }

  function startPaper(paper){
    if(!paper)return;currentPaper=paper;const id=deviceId();currentSession={schemaVersion:'ukmla-psa-session-v1',sessionId:core().uid('psa-session'),deviceId:id,paperId:paper.paperId,status:'active',startedAt:new Date().toISOString(),currentIndex:0,answers:{},flagged:{},itemMeta:{},remainingSeconds:paper.durationSeconds,lastTimerAt:Date.now()};engine().saveSession(currentSession);renderExam();
  }
  function touchTime(){
    if(!currentSession||!currentPaper)return;const item=currentPaper.items[currentSession.currentIndex];if(!item)return;const now=Date.now();if(lastItemEnteredAt){const meta=currentSession.itemMeta[item.id]||(currentSession.itemMeta[item.id]={timeSpentSeconds:0,lookupCount:0});meta.timeSpentSeconds+=Math.max(0,Math.round((now-lastItemEnteredAt)/1000));}lastItemEnteredAt=now;
  }
  function updateRemaining(){
    if(!currentSession||currentSession.status!=='active')return;const now=Date.now(),elapsed=Math.max(0,Math.floor((now-(currentSession.lastTimerAt||now))/1000));if(elapsed){currentSession.remainingSeconds=Math.max(0,currentSession.remainingSeconds-elapsed);currentSession.lastTimerAt=now;engine().saveSession(currentSession);}const timer=document.getElementById('psa-timer');if(timer)timer.textContent=formatTime(currentSession.remainingSeconds);if(currentSession.remainingSeconds<=0){stopTimer();touchTime();renderReview(true);}
  }
  function startTimer(){stopTimer();lastItemEnteredAt=Date.now();currentSession.lastTimerAt=Date.now();timerId=setInterval(updateRemaining,1000);}
  function stopTimer(){if(timerId){clearInterval(timerId);timerId=null;}}
  function navigate(index){touchTime();saveCurrentAnswer();currentSession.currentIndex=Math.max(0,Math.min(currentPaper.items.length-1,index));engine().saveSession(currentSession);renderExam();}
  function answerExists(item){const answer=currentSession.answers[item.id];if(!answer)return false;if(item.responseMode==='prescription')return Object.values(answer.prescription||{}).some(Boolean);if(item.responseMode==='single_select')return Boolean(answer.optionId);if(item.responseMode==='multi_select')return Boolean(answer.reviewIds?.length);if(item.responseMode==='numeric')return answer.numericValue!==''&&answer.numericValue!==undefined;return false;}

  function renderExam(){
    root=root||document.getElementById('quiz-workspace');if(!root||!currentSession||!currentPaper)return;stopTimer();const item=currentPaper.items[currentSession.currentIndex],answer=currentSession.answers[item.id]||{},meta=currentSession.itemMeta[item.id]||(currentSession.itemMeta[item.id]={timeSpentSeconds:0,lookupCount:0});const sectionMeta=paperSectionMeta(item);root.innerHTML=`<section class="psa-exam-shell"><header class="psa-exam-head"><div><span class="eyebrow">${escapeHtml(sectionMeta.label)}</span><strong>Question ${currentSession.currentIndex+1} of ${currentPaper.items.length}</strong></div><div class="psa-timer" id="psa-timer">${formatTime(currentSession.remainingSeconds)}</div></header><div class="progress-track"><div class="progress-fill" style="--value:${Math.round((currentSession.currentIndex+1)/currentPaper.items.length*100)}%"></div></div><div class="psa-exam-grid"><article class="quiz-card psa-question-card"><div class="topic-meta"><span>${item.marks} marks · ${escapeHtml(item.clinicalDomain)}</span><span>${escapeHtml(item.highRiskClass)}</span></div><h2 class="psa-stem">${escapeHtml(item.stem)}</h2><div class="psa-context">${escapeHtml(item.context)}</div>${responseHtml(item,answer)}<div class="psa-item-actions"><button class="btn ghost" id="psa-bnf">Open BNF <sup>${meta.lookupCount||0}</sup></button><button class="btn ${currentSession.flagged[item.id]?'danger':'ghost'}" id="psa-flag">${currentSession.flagged[item.id]?'Flagged':'Flag for review'}</button></div></article><aside class="quiz-card psa-nav-panel"><div class="psa-section-budget"><span>Suggested section budget</span><strong>${sectionMeta.timeMinutes} min in a full paper</strong></div><div class="psa-question-grid">${currentPaper.items.map((entry,index)=>`<button class="psa-q-dot ${index===currentSession.currentIndex?'current':''} ${answerExists(entry)?'answered':''} ${currentSession.flagged[entry.id]?'flagged':''}" data-psa-index="${index}">${index+1}</button>`).join('')}</div><div class="storage-row"><span>BNF lookups</span><strong>${Object.values(currentSession.itemMeta).reduce((sum,row)=>sum+Number(row.lookupCount||0),0)}</strong></div><div class="storage-row"><span>Answered</span><strong>${currentPaper.items.filter(answerExists).length}/${currentPaper.items.length}</strong></div></aside></div><footer class="psa-exam-footer"><button class="btn" id="psa-prev" ${currentSession.currentIndex===0?'disabled':''}>← Previous</button><button class="btn ghost" id="psa-review">Review paper</button><button class="btn primary" id="psa-next">${currentSession.currentIndex===currentPaper.items.length-1?'Review and submit':'Next →'}</button></footer></section>`;
    bindResponse(item);root.querySelectorAll('[data-psa-index]').forEach(button=>button.onclick=()=>navigate(Number(button.dataset.psaIndex)));root.querySelector('#psa-prev').onclick=()=>navigate(currentSession.currentIndex-1);root.querySelector('#psa-next').onclick=()=>{saveCurrentAnswer();if(currentSession.currentIndex===currentPaper.items.length-1)renderReview(false);else navigate(currentSession.currentIndex+1);};root.querySelector('#psa-review').onclick=()=>{saveCurrentAnswer();renderReview(false);};root.querySelector('#psa-flag').onclick=()=>{currentSession.flagged[item.id]=!currentSession.flagged[item.id];engine().saveSession(currentSession);renderExam();};root.querySelector('#psa-bnf').onclick=()=>{meta.lookupCount=(meta.lookupCount||0)+1;engine().saveSession(currentSession);window.open('https://bnf.nice.org.uk/','_blank','noopener');renderExam();};startTimer();
  }
  function responseHtml(item,answer){
    if(item.responseMode==='single_select')return`<div class="options psa-options">${item.options.map(option=>`<label class="option"><input type="radio" name="psa-option" value="${option.id}" ${answer.optionId===option.id?'checked':''}><span class="letter">${escapeHtml(option.id)}</span><span>${escapeHtml(option.text)}</span></label>`).join('')}</div>`;
    if(item.responseMode==='multi_select')return`<div class="psa-med-chart"><div class="psa-chart-head"><span>Select exactly two prescriptions</span><strong>${answer.reviewIds?.length||0}/2 selected</strong></div>${item.medicationList.map(entry=>`<label class="psa-med-row"><input type="checkbox" name="psa-review" value="${entry.id}" ${(answer.reviewIds||[]).includes(entry.id)?'checked':''}><strong>${escapeHtml(entry.drug)}</strong><span>${escapeHtml(entry.directions)}</span><small>${escapeHtml(entry.note)}</small></label>`).join('')}</div>`;
    if(item.responseMode==='numeric')return`<div class="psa-numeric"><div class="field"><label>Calculated value</label><input class="input" id="psa-number" inputmode="decimal" value="${escapeHtml(answer.numericValue??'')}"></div><div class="field"><label>Unit</label><input class="input" id="psa-unit" value="${escapeHtml(answer.unit||'')}"></div><button class="btn ghost" id="psa-calculator">Calculator</button></div>`;
    const value=answer.prescription||{};return`<div class="psa-prescription-form"><div class="field"><label>Medicine</label><input class="input" data-rx="medicine" value="${escapeHtml(value.medicine||'')}"></div><div class="field"><label>Formulation</label><input class="input" data-rx="formulation" value="${escapeHtml(value.formulation||'')}"></div><div class="field"><label>Strength</label><input class="input" data-rx="strength" value="${escapeHtml(value.strength||'')}"></div><div class="field"><label>Dose</label><input class="input" data-rx="dose" value="${escapeHtml(value.dose||'')}"></div><div class="field"><label>Route</label><input class="input" data-rx="route" value="${escapeHtml(value.route||'')}"></div><div class="field"><label>Frequency</label><input class="input" data-rx="frequency" value="${escapeHtml(value.frequency||'')}"></div><div class="field"><label>Duration</label><input class="input" data-rx="duration" value="${escapeHtml(value.duration||'')}"></div><div class="field psa-wide"><label>Additional instructions</label><input class="input" data-rx="instructions" value="${escapeHtml(value.instructions||'')}"></div></div>`;
  }
  function bindResponse(item){
    if(item.responseMode==='single_select')root.querySelectorAll('input[name="psa-option"]').forEach(input=>input.onchange=saveCurrentAnswer);
    if(item.responseMode==='multi_select')root.querySelectorAll('input[name="psa-review"]').forEach(input=>input.onchange=event=>{const selected=[...root.querySelectorAll('input[name="psa-review"]:checked')];if(selected.length>2){event.target.checked=false;core().toast('Select exactly two prescriptions.');}saveCurrentAnswer();});
    if(item.responseMode==='numeric'){root.querySelector('#psa-number').oninput=saveCurrentAnswer;root.querySelector('#psa-unit').oninput=saveCurrentAnswer;root.querySelector('#psa-calculator').onclick=showCalculator;}
    if(item.responseMode==='prescription')root.querySelectorAll('[data-rx]').forEach(input=>input.oninput=saveCurrentAnswer);
  }
  function saveCurrentAnswer(){
    if(!currentSession||!currentPaper||!root)return;const item=currentPaper.items[currentSession.currentIndex];if(item.responseMode==='single_select'){currentSession.answers[item.id]={optionId:root.querySelector('input[name="psa-option"]:checked')?.value||''};}
    else if(item.responseMode==='multi_select'){currentSession.answers[item.id]={reviewIds:[...root.querySelectorAll('input[name="psa-review"]:checked')].map(input=>input.value)};}
    else if(item.responseMode==='numeric'){currentSession.answers[item.id]={numericValue:root.querySelector('#psa-number')?.value??'',unit:root.querySelector('#psa-unit')?.value||''};}
    else{const prescription={};root.querySelectorAll('[data-rx]').forEach(input=>prescription[input.dataset.rx]=input.value);currentSession.answers[item.id]={prescription};}
    engine().saveSession(currentSession);
  }
  function showCalculator(){
    const overlay=document.createElement('div');overlay.className='psa-overlay';overlay.innerHTML='<div class="panel psa-calculator-panel"><h2>Basic calculator</h2><input class="input" id="psa-calc-expression" inputmode="decimal" placeholder="e.g. 250 * 4 / 1000"><div class="metric-big" id="psa-calc-result">—</div><div class="card-actions"><button class="btn primary" id="psa-calc-run">Calculate</button><button class="btn ghost" id="psa-calc-close">Close</button></div></div>';document.body.appendChild(overlay);overlay.querySelector('#psa-calc-run').onclick=()=>{const expression=overlay.querySelector('#psa-calc-expression').value;if(!/^[\d\s.+\-*/()]+$/.test(expression)){overlay.querySelector('#psa-calc-result').textContent='Invalid';return;}try{overlay.querySelector('#psa-calc-result').textContent=String(Function(`"use strict";return (${expression})`)());}catch(_){overlay.querySelector('#psa-calc-result').textContent='Invalid';}};overlay.querySelector('#psa-calc-close').onclick=()=>overlay.remove();
  }

  function renderReview(timeExpired){
    stopTimer();touchTime();saveCurrentAnswer();currentSession.status='review';engine().saveSession(currentSession);const answered=currentPaper.items.filter(answerExists).length,flagged=Object.values(currentSession.flagged).filter(Boolean).length;root.innerHTML=`<section class="psa-review-page"><div class="page-head"><div><div class="eyebrow">${timeExpired?'Time expired':'Paper review'}</div><h1>${answered}/${currentPaper.items.length} answered</h1><p>${flagged} flagged. Review any item before submitting. Once marking starts, answers cannot be changed.</p></div></div><div class="psa-review-grid">${schema().SECTIONS.filter(section=>currentPaper.counts[section.id]).map(section=>`<article class="metric-card"><h3>${escapeHtml(section.label)}</h3><div class="psa-question-grid">${currentPaper.items.map((item,index)=>item.sectionId===section.id?`<button class="psa-q-dot ${answerExists(item)?'answered':''} ${currentSession.flagged[item.id]?'flagged':''}" data-review-index="${index}">${index+1}</button>`:'').join('')}</div></article>`).join('')}</div><article class="panel psa-submit-panel"><div class="field" ${hasPrescriptionItems(currentPaper)?'':'hidden'}><label>Temporary API key for audited prescription marking</label><input class="input" id="psa-marking-key" type="password" autocomplete="off" placeholder="Paste session key"></div><p>Objective items are marked deterministically. Prescription responses receive primary rubric marking, an independent safety-critical audit, and adjudication where the two disagree.</p><div class="card-actions"><button class="btn" id="psa-return">Return to paper</button><button class="btn primary" id="psa-submit">Submit and mark</button></div></article><section class="quiz-card" id="psa-marking-progress" hidden><div class="topic-meta"><span>Marking checkpoints</span><strong id="psa-marking-percent">0%</strong></div><div class="progress-track"><div class="progress-fill" id="psa-marking-fill" style="--value:0%"></div></div><div class="checkpoint-list" id="psa-marking-checkpoints">${markingCheckpointHtml(null)}</div><p id="psa-marking-message">Ready.</p></section></section>`;root.querySelectorAll('[data-review-index]').forEach(button=>button.onclick=()=>{currentSession.status='active';engine().saveSession(currentSession);navigate(Number(button.dataset.reviewIndex));});root.querySelector('#psa-return').onclick=()=>{currentSession.status='active';engine().saveSession(currentSession);renderExam();};root.querySelector('#psa-submit').onclick=submitAndMark;
  }
  function markingCheckpointHtml(job){return schema().MARKING_STAGES.map((stage,index)=>{const active=job?.currentStage===stage.id&&job?.status!=='complete';const done=job&&(job.stageIndex>index||job.status==='complete');return`<div class="checkpoint ${done?'done':''} ${active?'active':''}"><span class="checkpoint-dot"></span><span>${escapeHtml(stage.label)}</span></div>`;}).join('');}
  function updateMarking(job){const panel=root?.querySelector('#psa-marking-progress');if(!panel)return;panel.hidden=false;const percent=job?.percent||0;root.querySelector('#psa-marking-percent').textContent=`${percent}%`;root.querySelector('#psa-marking-fill').style.setProperty('--value',`${percent}%`);root.querySelector('#psa-marking-message').textContent=job?.lastMessage||'';root.querySelector('#psa-marking-checkpoints').innerHTML=markingCheckpointHtml(job);}
  async function submitAndMark(){
    if(markingRunning)return;const needsKey=hasPrescriptionItems(currentPaper);const token=clean(root.querySelector('#psa-marking-key')?.value||sessionToken);if(needsKey&&token.length<20){core().toast('Paste the temporary key for prescription marking.');return;}markingRunning=true;root.querySelectorAll('button').forEach(button=>button.disabled=true);try{const attempt=await engine().markSession({apiKey:token,paper:currentPaper,session:currentSession,job:engine().loadMarkingJob()});currentSession=null;sessionToken='';renderResult(attempt);}catch(error){core().toast(`Marking stopped: ${error.message}`);updateMarking(engine().loadMarkingJob());root.querySelectorAll('button').forEach(button=>button.disabled=false);}finally{markingRunning=false;}
  }
  function renderResult(attempt){
    const sections=Object.entries(attempt.sectionBreakdown);root.innerHTML=`<section class="psa-result"><article class="hero-card psa-result-hero"><div class="eyebrow">PSA practice complete</div><div class="boast-number">${attempt.awardedMarks}/${attempt.totalMarks}</div><h2>${attempt.percentage}%</h2><p>${attempt.lookupCount} BNF lookups · ${formatTime(attempt.durationSeconds)} total time</p></article><section class="analytics-grid">${sections.map(([id,row])=>`<article class="metric-card"><h3>${escapeHtml(schema().section(id).label)}</h3><div class="metric-big">${Math.round(row.awarded*10)/10}/${row.available}</div><p>${row.available?Math.round(row.awarded/row.available*100):0}% · ${row.safetyCritical} safety-critical flags</p></article>`).join('')}</section><article class="panel"><h2>Item feedback</h2><div class="psa-feedback-list">${attempt.itemResults.map((result,index)=>{const item=currentPaper.items.find(entry=>entry.id===result.itemId);return`<details><summary>${index+1}. ${escapeHtml(item?.sectionLabel||result.sectionId)} — ${result.awardedMarks}/${result.maxMarks}${result.safetyCritical?' · safety-critical':''}</summary><p>${escapeHtml(result.feedback||'')}</p><p><strong>Model answer:</strong> ${escapeHtml(item?.modelAnswer||'')}</p><p><strong>BNF route:</strong> ${escapeHtml((item?.bnfTargets||[]).join(' → '))}</p></details>`;}).join('')}</div></article><div class="card-actions"><button class="btn primary" id="psa-analyse">Open PSA analytics</button><button class="btn" id="psa-new-paper">New PSA paper</button></div></section>`;root.querySelector('#psa-analyse').onclick=renderAnalytics;root.querySelector('#psa-new-paper').onclick=renderSetup;
  }

  function attempts(){return engine().attempts();}
  function aggregateAnalytics(){
    const rows=attempts(),sections={};for(const meta of schema().SECTIONS)sections[meta.id]={id:meta.id,label:meta.label,awarded:0,available:0,attempts:0,safetyCritical:0,time:0,lookups:0};const errors={},risk={},domain={};let totalAwarded=0,totalAvailable=0,totalLookups=0,totalTime=0,totalItems=0,safetyCritical=0;
    for(const attempt of rows){totalAwarded+=attempt.awardedMarks;totalAvailable+=attempt.totalMarks;totalLookups+=attempt.lookupCount||0;totalTime+=attempt.durationSeconds||0;for(const [id,row] of Object.entries(attempt.sectionBreakdown||{})){const target=sections[id]||{id,label:id,awarded:0,available:0,attempts:0,safetyCritical:0,time:0,lookups:0};target.awarded+=row.awarded;target.available+=row.available;target.attempts+=row.items;target.safetyCritical+=row.safetyCritical||0;sections[id]=target;totalItems+=row.items||0;safetyCritical+=row.safetyCritical||0;}for(const result of attempt.itemResults||[]){for(const tag of result.errorTags||[])errors[tag]=(errors[tag]||0)+1;}const paper=engine().paperById(attempt.paperId);for(const item of paper?.items||[]){const result=attempt.itemResults.find(row=>row.itemId===item.id);if(!result)continue;const riskRow=risk[item.highRiskClass]||(risk[item.highRiskClass]={awarded:0,available:0});riskRow.awarded+=result.awardedMarks;riskRow.available+=result.maxMarks;const domainRow=domain[item.clinicalDomain]||(domain[item.clinicalDomain]={awarded:0,available:0});domainRow.awarded+=result.awardedMarks;domainRow.available+=result.maxMarks;}}
    return{rows,sections:Object.values(sections),errors,risk,domain,totalAwarded,totalAvailable,totalLookups,totalTime,totalItems,safetyCritical,percentage:totalAvailable?Math.round(totalAwarded/totalAvailable*1000)/10:0};
  }
  function renderAnalytics(){
    stopTimer();const app=document.getElementById('app');if(!app)return;root=app;const data=aggregateAnalytics();document.getElementById('page-kicker').textContent='Prescribing Safety Assessment';document.getElementById('page-title').textContent='PSA analytics';app.innerHTML=`<div class="page-head"><div><div class="eyebrow">PSA learning record</div><h1>${data.rows.length} completed papers</h1><p>Performance by official section, high-risk medicine, clinical domain, time and BNF use.</p></div><div class="page-actions"><button class="btn primary" id="psa-copy-summary">Copy PSA summary</button><button class="btn" id="psa-download-csv">Download PSA CSV</button><button class="btn ghost" id="psa-back-sba">SBA analytics</button></div></div><section class="analytics-grid"><article class="metric-card"><h3>Overall marks</h3><div class="metric-big">${data.percentage}%</div><p>${Math.round(data.totalAwarded*10)/10}/${data.totalAvailable} marks</p></article><article class="metric-card"><h3>BNF navigation</h3><div class="metric-big">${data.totalLookups}</div><p>${data.totalItems?Math.round(data.totalLookups/data.totalItems*100)/100:0} lookups per item</p></article><article class="metric-card"><h3>Timing</h3><div class="metric-big">${data.totalItems?Math.round(data.totalTime/data.totalItems):0}s</div><p>average per item</p></article><article class="metric-card"><h3>Safety-critical</h3><div class="metric-big">${data.safetyCritical}</div><p>responses flagged</p></article>${data.sections.map(row=>`<article class="metric-card"><h3>${escapeHtml(row.label)}</h3><div class="metric-big">${row.available?Math.round(row.awarded/row.available*100):0}%</div><p>${Math.round(row.awarded*10)/10}/${row.available} marks · ${row.attempts} items</p></article>`).join('')}<article class="metric-card"><h3>Frequent error types</h3><div class="rank-list">${rankRows(data.errors)}</div></article><article class="metric-card"><h3>High-risk medicines</h3><div class="rank-list">${scoreRows(data.risk)}</div></article><article class="metric-card"><h3>Clinical domains</h3><div class="rank-list">${scoreRows(data.domain)}</div></article></section>`;app.querySelector('#psa-copy-summary').onclick=()=>core().copyText(psaSummary(data),'PSA analytics copied');app.querySelector('#psa-download-csv').onclick=()=>core().downloadText(psaCsv(data.rows),`ukmla-psa-${new Date().toISOString().slice(0,10)}.csv`,'text/csv');app.querySelector('#psa-back-sba').onclick=()=>core().go('analytics');
  }
  function rankRows(object){const entries=Object.entries(object).sort((a,b)=>b[1]-a[1]).slice(0,10);return entries.length?entries.map(([name,count])=>`<div class="rank-row"><span>${escapeHtml(name.replace(/_/g,' '))}</span><span>${count}</span></div>`).join(''):'<p>No errors recorded.</p>';}
  function scoreRows(object){const entries=Object.entries(object).map(([name,row])=>[name,row.available?Math.round(row.awarded/row.available*100):0,row]).sort((a,b)=>a[1]-b[1]).slice(0,10);return entries.length?entries.map(([name,percent,row])=>`<div class="rank-row"><span>${escapeHtml(name)}</span><span>${percent}% · ${Math.round(row.awarded*10)/10}/${row.available}</span></div>`).join(''):'<p>No data recorded.</p>';}
  function psaSummary(data){return['PSA PRACTICE ANALYTICS',`Generated: ${new Date().toLocaleString()}`,'',`Completed papers: ${data.rows.length}`,`Overall marks: ${Math.round(data.totalAwarded*10)/10}/${data.totalAvailable} (${data.percentage}%)`,`BNF lookups: ${data.totalLookups}`,`Average time per item: ${data.totalItems?Math.round(data.totalTime/data.totalItems):0} seconds`,`Safety-critical responses: ${data.safetyCritical}`,'','SECTION PERFORMANCE',...data.sections.map(row=>`${row.label}: ${row.available?Math.round(row.awarded/row.available*100):0}% — ${Math.round(row.awarded*10)/10}/${row.available} marks — ${row.attempts} items`),'','FREQUENT ERROR TAGS',...Object.entries(data.errors).sort((a,b)=>b[1]-a[1]).map(([tag,count])=>`${tag}: ${count}`),'','INTERPRETATION REQUEST','Analyse my safe-prescribing performance. Identify whether my main limitation is clinical selection, prescription detail, calculations, units, prescription review, BNF navigation, time allocation, or safety-critical prescribing. Recommend the next 50 practice items by PSA section and high-risk medicine.'].join('\n');}
  function psaCsv(rows){const columns=['attempt_id','paper_id','mode','started_at','completed_at','awarded_marks','total_marks','percentage','duration_seconds','bnf_lookups','section_id','section_awarded','section_available','safety_critical'];const quote=value=>`"${String(value??'').replace(/"/g,'""')}"`;const lines=[columns.join(',')];for(const attempt of rows)for(const [id,row] of Object.entries(attempt.sectionBreakdown||{}))lines.push([attempt.attemptId,attempt.paperId,attempt.mode,attempt.startedAt,attempt.completedAt,attempt.awardedMarks,attempt.totalMarks,attempt.percentage,attempt.durationSeconds,attempt.lookupCount,id,row.awarded,row.available,row.safetyCritical].map(quote).join(','));return lines.join('\n');}

  document.addEventListener('ukmlaPsaGenerationProgress',event=>updateGeneration(event.detail));
  document.addEventListener('ukmlaPsaMarkingProgress',event=>updateMarking(event.detail));
  window.addEventListener('hashchange',()=>setTimeout(integrate,0));
  const observer=new MutationObserver(()=>requestAnimationFrame(integrate));
  function init(){const app=document.getElementById('app');if(app)observer.observe(app,{childList:true});integrate();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.UKMLA_PSA={mount,renderAnalytics};
})();
