(function(){
'use strict';
const PAD_ID='ukmla-4Jq9QYF2vHc8nLz6WmRpT3xA';
const KEYS=['ukmlaQuizProgressV1','ukmlaAspectStatusV2','ukmlaAiPromptCheckedV1','ukmlaAiDecisionDataV1','ukmlaAiGeneratedQuizSetsV1','ukmlaLearningEventsV1','ukmlaLearningRegistryV1','ukmlaCoverageStateV1','ukmlaKnowledgePackStatsV1','ukmlaV2StateV1','ukmlaV2ReviewedV1','ukmlaPsaPapersV1','ukmlaPsaActiveSessionsV1','ukmlaPsaAttemptsV1','ukmlaPsaGenerationJobV1','ukmlaPsaMarkingJobV1','ukmlaPsaUiStateV1'];
let root=null,firebasePromise=null,busy=false;
function core(){return window.UKMLA_V2;}
function parse(value,fallback){try{return JSON.parse(value||'null')??fallback;}catch(_){return fallback;}}
function status(message){const node=root?.querySelector('#sync-status');if(node)node.textContent=message;const indicator=document.getElementById('sync-indicator');if(indicator)indicator.textContent=message;}
function setBusy(value){busy=value;root?.querySelectorAll('button').forEach(button=>button.disabled=value);}
function localValues(){const values={};for(const key of KEYS){const value=localStorage.getItem(key);if(value!==null)values[key]=value;}return values;}
function backupPayload(){return{schemaVersion:'ukmla-v2-backup-2',exportedAt:new Date().toISOString(),deviceId:localStorage.getItem('ukmlaRemoteDeviceIdV1')||'',values:localValues()};}
function mergeEvents(localValue,remoteValue){const map=new Map();[...parse(localValue,[]),...parse(remoteValue,[])].forEach(event=>{if(event?.id)map.set(event.id,event);});return JSON.stringify([...map.values()].sort((a,b)=>String(a.at||'').localeCompare(String(b.at||''))));}
function mergeObjects(localValue,remoteValue){const local=parse(localValue,{}),remote=parse(remoteValue,{}),result={...remote};for(const[key,value]of Object.entries(local)){const existing=result[key],localDate=String(value?.updatedAt||value?.createdAt||''),remoteDate=String(existing?.updatedAt||existing?.createdAt||'');if(!existing||localDate>=remoteDate)result[key]=value;}return JSON.stringify(result);}
function mergeNewest(localValue,remoteValue){const local=parse(localValue,null),remote=parse(remoteValue,null);if(!local)return remoteValue;if(!remote)return localValue;const localDate=String(local.updatedAt||local.createdAt||''),remoteDate=String(remote.updatedAt||remote.createdAt||'');return localDate>=remoteDate?JSON.stringify(local):JSON.stringify(remote);}
function mergeArrayById(localValue,remoteValue,idFields,limit=100){const map=new Map();for(const item of [...parse(remoteValue,[]),...parse(localValue,[])]){const id=idFields.map(field=>item?.[field]).find(Boolean);if(!id)continue;const existing=map.get(id),itemDate=String(item?.updatedAt||item?.completedAt||item?.generatedAt||item?.createdAt||''),existingDate=String(existing?.updatedAt||existing?.completedAt||existing?.generatedAt||existing?.createdAt||'');if(!existing||itemDate>=existingDate)map.set(id,item);}return JSON.stringify([...map.values()].sort((a,b)=>String(b.updatedAt||b.completedAt||b.generatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.completedAt||a.generatedAt||a.createdAt||''))).slice(0,limit));}
function mergeRegistry(localValue,remoteValue){const local=parse(localValue,{version:1,topics:{},conditions:{}}),remote=parse(remoteValue,{version:1,topics:{},conditions:{}});return JSON.stringify({version:Math.max(Number(local.version)||1,Number(remote.version)||1),topics:{...(remote.topics||{}),...(local.topics||{})},conditions:{...(remote.conditions||{}),...(local.conditions||{})}});}
function mergeCoverage(localValue,remoteValue){const local=parse(localValue,{cycle:1,completedCycles:0,covered:[]}),remote=parse(remoteValue,{cycle:1,completedCycles:0,covered:[]}),lc=Number(local.cycle)||1,rc=Number(remote.cycle)||1;if(lc>rc)return JSON.stringify(local);if(rc>lc)return JSON.stringify(remote);return JSON.stringify({...remote,...local,cycle:lc,completedCycles:Math.max(Number(local.completedCycles)||0,Number(remote.completedCycles)||0),covered:[...new Set([...(remote.covered||[]),...(local.covered||[])])],updatedAt:new Date().toISOString()});}
function mergeProgress(localValue,remoteValue){const local=parse(localValue,{}),remote=parse(remoteValue,{}),result={...remote};for(const[key,value]of Object.entries(local)){if(key.startsWith('__')){result[key]=value;continue;}const existing=result[key];if(!existing||Number(value?.attempts||0)>=Number(existing?.attempts||0))result[key]=value;}return JSON.stringify(result);}
function mergeSets(localValue,remoteValue){return mergeArrayById(localValue,remoteValue,['quizId','generatedAt'],50);}
function mergeValue(key,localValue,remoteValue){
  if(key==='ukmlaLearningEventsV1')return mergeEvents(localValue,remoteValue);
  if(key==='ukmlaLearningRegistryV1')return mergeRegistry(localValue,remoteValue);
  if(key==='ukmlaCoverageStateV1')return mergeCoverage(localValue,remoteValue);
  if(key==='ukmlaQuizProgressV1')return mergeProgress(localValue,remoteValue);
  if(key==='ukmlaAiGeneratedQuizSetsV1')return mergeSets(localValue,remoteValue);
  if(key==='ukmlaPsaPapersV1')return mergeArrayById(localValue,remoteValue,['paperId'],20);
  if(key==='ukmlaPsaAttemptsV1')return mergeArrayById(localValue,remoteValue,['attemptId'],150);
  if(['ukmlaKnowledgePackStatsV1','ukmlaV2ReviewedV1','ukmlaPsaActiveSessionsV1'].includes(key))return mergeObjects(localValue,remoteValue);
  if(['ukmlaPsaGenerationJobV1','ukmlaPsaMarkingJobV1','ukmlaPsaUiStateV1'].includes(key))return mergeNewest(localValue,remoteValue);
  return localValue??remoteValue;
}
function mergeRemote(values){for(const key of KEYS){const local=localStorage.getItem(key),remote=values?.[key];if(remote===undefined&&local===null)continue;const merged=mergeValue(key,local,remote);if(merged!==null&&merged!==undefined)localStorage.setItem(key,String(merged));}document.dispatchEvent(new Event('ukmlaRemoteDataImported'));}
async function firebase(){if(firebasePromise)return firebasePromise;firebasePromise=(async()=>{status('Connecting to Firebase…');const appMod=await import('https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js');const dbMod=await import('https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js');const config=window.UKMLA_V2_FIREBASE_CONFIG;if(!config)throw new Error('Firebase configuration is unavailable.');const app=appMod.getApps().length?appMod.getApp():appMod.initializeApp(config);const db=dbMod.getDatabase(app),ref=dbMod.ref(db,`ukmlaPads/${PAD_ID.replace(/[^A-Za-z0-9_-]/g,'-')}/state`);return{dbMod,ref};})();return firebasePromise;}
async function pull(){if(busy)return;setBusy(true);try{const{dbMod,ref}=await firebase();status('Downloading and merging cloud data…');const snapshot=await dbMod.get(ref),remote=snapshot.val();if(!remote?.values){status('Cloud pad is empty.');return;}mergeRemote(remote.values);status('Cloud data merged. Reloading…');setTimeout(()=>location.reload(),650);}catch(error){status(`Pull failed: ${error.message}`);}finally{setBusy(false);}}
async function push(){if(busy)return;setBusy(true);try{const{dbMod,ref}=await firebase();status('Merging current cloud data before upload…');const snapshot=await dbMod.get(ref),remote=snapshot.val();if(remote?.values)mergeRemote(remote.values);await dbMod.set(ref,{updatedAt:Date.now(),origin:localStorage.getItem('ukmlaRemoteDeviceIdV1')||'v2',values:localValues()});status(`Merged and pushed at ${new Date().toLocaleTimeString()}.`);}catch(error){status(`Push failed: ${error.message}`);}finally{setBusy(false);}}
function downloadBackup(){core().downloadText(JSON.stringify(backupPayload(),null,2),`ukmla-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json');}
async function importBackup(file){try{const payload=JSON.parse(await file.text());if(!payload?.values||typeof payload.values!=='object')throw new Error('This is not a UKMLA backup.');mergeRemote(payload.values);status('Backup imported. Reloading…');setTimeout(()=>location.reload(),500);}catch(error){status(`Import failed: ${error.message}`);}}
function storageSize(){let total=0;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);total+=(key?.length||0)+(localStorage.getItem(key)?.length||0);}return total*2;}
function formatBytes(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1048576).toFixed(2)} MB`;}
function mount(container){root=container;root.innerHTML=`<div class="page-head"><div><div class="eyebrow">Local-first data control</div><h1>Sync & backup</h1><p>No network connection is opened until you press Pull or Push. Both actions merge unique learning events and PSA attempts rather than replacing them.</p></div></div><section class="sync-grid"><article class="panel"><h2>Firebase cloud pad</h2><p id="sync-status" style="color:var(--muted)">Disconnected. Local data remains available.</p><div class="card-actions"><button class="btn primary" id="sync-pull">Pull and merge</button><button class="btn" id="sync-push">Merge and push</button></div></article><article class="panel"><h2>Complete backup</h2><p>Export all progress, events, generated quizzes, PSA papers, active device sessions and review state.</p><div class="card-actions"><button class="btn" id="sync-export">Download backup</button><button class="btn ghost" id="sync-import">Import backup</button><input id="sync-import-file" type="file" accept="application/json,.json" hidden></div></article><article class="panel"><h2>Browser storage</h2><div class="storage-row"><span>Used</span><strong>${formatBytes(storageSize())}</strong></div><div class="storage-row"><span>Learning events</span><strong>${core().events().length}</strong></div><div class="storage-row"><span>Generated SBA sets</span><strong>${core().loadJson(core().STORAGE.sets,[]).length}</strong></div><div class="storage-row"><span>PSA attempts</span><strong>${parse(localStorage.getItem('ukmlaPsaAttemptsV1'),[]).length}</strong></div><div class="storage-row"><span>PSA papers</span><strong>${parse(localStorage.getItem('ukmlaPsaPapersV1'),[]).length}</strong></div><div class="storage-row"><span>Knowledge packs</span><strong>${Object.keys(core().loadJson(core().STORAGE.knowledge,{})).length}</strong></div></article></section>`;root.querySelector('#sync-pull').onclick=pull;root.querySelector('#sync-push').onclick=push;root.querySelector('#sync-export').onclick=downloadBackup;root.querySelector('#sync-import').onclick=()=>root.querySelector('#sync-import-file').click();root.querySelector('#sync-import-file').onchange=event=>{const file=event.target.files[0];if(file)importBackup(file);};}
window.UKMLA_V2_SYNC={mount};
})();
